---
title: "Microridge Curviness Analysis"
output: html_document
---

This program takes pixel coordinate data from images of microridges and analyzes microridge 
curviness. Microridges are small ridges formed by actin protrusions on the surface of skin cells 
which are thought to function in mucus retention. These microridges are imaged on the surface 
of zebrafish skin cells by using LifeAct-GFP transgenic lines, making microridges 
fluorescent. Another member of the lab took these images and has a program that deconvolutes 
this data and turns it into a series of coordinates for each ridge. This program uses that 
existing data and returns an excel file containing a measure of curviness for each microridge.

### Introduction
#### Microridges
Background on microridges.  
Microridge pictures.
#### Analysis
This is how the program analyzes the data.

### Program Usage

#### Requirements
You need to install these things.  
You need these versions of those things.  
The data needs to look like this.
 * You can use this program (cite Aaron's paper) to convert miroridge images to pixels and 
then use this program with the output coordinates..
#### Usage Instructions
This is how to name the input files and how to run the program. These are the outputs that 
the program will give.
#### Test Files
This is a description of how to test that the program is working right.

### Author
* Hannah Markovic
    * Biology PhD student at the University of Oregon
    * B.S. in Molecular, Cell and Developmental Biology with minor in Biomedical Research, UCLA
    * contact: hannah.markovic@gmail.com
* This program was created as the final project for the class EEB 177, Spring 2019

### Acknowledgements
* Aaron van Loon - data
* Dr. Emily Curd and Daniel Chavez - guidance

### References
* papers
* math